*** Starting uWSGI 2.0.12-debian (64bit) on [Fri Mar 30 14:24:45 2018] ***
compiled with version: 5.4.0 20160609 on 31 August 2017 21:02:04
os: Linux-4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018
nodename: ip-172-31-44-246
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/hamza/PAP_backend
writing pidfile to /home/hamza/PAP_backend/app.pid
detected binary path: /usr/bin/uwsgi-core
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3900
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:3033 fd 3
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
Set PythonHome to /home/hamza/PAP_backend
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x12937b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
added /home/hamza/PAP_backend/ to pythonpath.
Traceback (most recent call last):
  File "/home/hamza/PAP_backend/app.py", line 10, in <module>
    from model.ModelManager import mManager
  File "/home/hamza/PAP_backend/model/ModelManager.py", line 1, in <module>
    from src.inference.classify import classify
  File "/home/hamza/PAP_backend/model/src/inference/classify.py", line 7, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/home/hamza/PAP_backend/app.py", line 10, in <module>
    from model.ModelManager import mManager
  File "/home/hamza/PAP_backend/model/ModelManager.py", line 1, in <module>
    from src.inference.classify import classify
  File "/home/hamza/PAP_backend/model/src/inference/classify.py", line 7, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 14837, cores: 1)
